/**
 * 
 */
package core.disService;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.uncommons.maths.random.MersenneTwisterRNG;

import core.DTNSim;
import core.ExponentialDecayDistribution;
import core.SeedGeneratorHelper;
import core.Settings;
import core.SimError;

/**
 * Class that implements the concept of a list of subscriptions
 * @author Alessandro Morelli
 *
 */
public class SubscriptionListManager {
	
	private enum RandomNumberOfSubscriptionsDistribution {UNIFORM, EXPONENTIALLY_DECAYING}
	
	private ArrayList<Integer> subscriptionList;

	private int maxSubID;
	private int minNumberOfSubscriptions;
	private int maxNumberOfSubscriptions;
	private boolean areSubscriptionsRandom;
	
	/** The highest SubscriptionID used in the simulation */
	public static int MAX_SUB_ID_OF_SIMULATION = Integer.MIN_VALUE;
	public static int MAX_NUMBER_OF_SUBSCRIPTIONS = 0;
	
	private static MersenneTwisterRNG RANDOM_ID_GENERATOR = null;
	private static long RANDOM_ID_GENERATOR_SEED = 666;
	private static RandomNumberOfSubscriptionsDistribution RandomDistribution =
			RandomNumberOfSubscriptionsDistribution.UNIFORM;
	private final static double DefaultDecayRate = 3.5;
	
	/** Value to specify errors or invalid subscription IDs */
	public static final int INVALID_SUB_ID = -1;
	/** Value to be used whenever no subscriptions are generated by the node */
	public static final int DEFAULT_SUB_ID = 0;

	/** The value of the seed for the random numbers generator. */
	public static final String SUB_ID_RND_SEED_S = "subIDRndSeed";
	/** The distribution from which to pick the number of subscriptions of a node. */
	public static final String SUB_ID_RND_DISTRIBUTION_S = "subIDRndDistribution";
	/** Max number of subscriptions -setting id ({@value}). int.
	 * If not specified, the value is computed from the number of subIDs specified. */
	public static final String MIN_NROF_SUBSCRIPTIONS = "minNrofSubscriptions";
	/** If not specified, the value is computed from the number of subIDs specified. */
	public static final String MAX_NROF_SUBSCRIPTIONS = "maxNrofSubscriptions";
	/** Highest valid ID for a subscription -setting id ({@value}). int.
	 * If not specified, the value is computed from the highest ID specified. */
	public static final String MAX_SUB_ID = "maxSubID";
	/** List of subscriptions the node performed -setting id ({@value}). Array of int.
	 * If not specified, the subscriptions are randomly generated. */
	public static final String GROUP_SUBSCRIPTION = "subIDs";

	/** The max number of subscriptions randomly generated a node can subscribe to */
	private static final int DEFAULT_MIN_NROF_SUBSCRIPTIONS = 1;
	/** The max number of subscriptions randomly generated a node can subscribe to */
	private static final int DEFAULT_MAX_NROF_SUBSCRIPTIONS = 5;
	/** The max subscription ID allowed for randomly generated subscriptions */
	private static final int DEFAULT_MAX_SUB_ID = 10;
	
	
	static {
		DTNSim.registerForReset(SubscriptionListManager.class.getCanonicalName());
		reset();
	}
	
	static private int getRandomID(int maxSubID) {
		return RANDOM_ID_GENERATOR.nextInt(maxSubID);
	}
	
	static private double getRandomDouble() {
		return RANDOM_ID_GENERATOR.nextDouble();
	}
	
	static public void reset() {
		RANDOM_ID_GENERATOR = null;
	}
	
	public SubscriptionListManager() {
		this.minNumberOfSubscriptions = DEFAULT_MIN_NROF_SUBSCRIPTIONS;
		this.maxNumberOfSubscriptions = DEFAULT_MAX_NROF_SUBSCRIPTIONS;
		this.maxSubID = DEFAULT_MAX_SUB_ID;
		this.areSubscriptionsRandom = true;
		this.subscriptionList = new ArrayList<Integer>();
		
		MAX_SUB_ID_OF_SIMULATION = Math.max(MAX_SUB_ID_OF_SIMULATION, this.maxSubID);
		
		if (RANDOM_ID_GENERATOR == null) {
			RANDOM_ID_GENERATOR = new MersenneTwisterRNG(
					SeedGeneratorHelper.get16BytesSeedFromValue(RANDOM_ID_GENERATOR_SEED));
		}
		randomizeSubscriptions();
	}
	
	public SubscriptionListManager(Settings s) throws ParseException {
		this.subscriptionList = new ArrayList<Integer>();
		
		if (s.contains(GROUP_SUBSCRIPTION)) {
			int ids[] = s.getCsvInts(GROUP_SUBSCRIPTION);
			if (ids.length > 0) {
				Arrays.sort(ids);
				if ((ids.length > 0) && (ids[0] > 0)) {
					for (int id : ids) {
						addSubscriptionToList(id);
					}
					
					this.minNumberOfSubscriptions = ids.length;
					this.maxNumberOfSubscriptions = ids.length;
					this.maxSubID = ids[ids.length - 1];
					this.areSubscriptionsRandom = false;
				}
				else if (ids[0] == 0) {
					throw new SimError("Invalid value for a subscription ID");
				}
				
				// In case of negative values, subscriptions will be randomly generated below
			}
		}

		if (this.subscriptionList.size() == 0) {
			// Parsing was unsuccessful or the first element in the list was "-1" or lower
			RandomDistribution = s.contains(SUB_ID_RND_DISTRIBUTION_S) ?
					RandomNumberOfSubscriptionsDistribution.values()[s.getInt(SUB_ID_RND_DISTRIBUTION_S)] :
					RandomNumberOfSubscriptionsDistribution.UNIFORM;
			this.minNumberOfSubscriptions = s.contains(MIN_NROF_SUBSCRIPTIONS) ?
					s.getInt(MIN_NROF_SUBSCRIPTIONS) : DEFAULT_MIN_NROF_SUBSCRIPTIONS;
			this.maxNumberOfSubscriptions = s.contains(MAX_NROF_SUBSCRIPTIONS) ?
					s.getInt(MAX_NROF_SUBSCRIPTIONS) : DEFAULT_MAX_NROF_SUBSCRIPTIONS;
			this.minNumberOfSubscriptions = Math.min(this.minNumberOfSubscriptions,
														this.maxNumberOfSubscriptions);
			this.maxSubID = s.contains(MAX_SUB_ID) ? s.getInt(MAX_SUB_ID) : DEFAULT_MAX_SUB_ID;
			
			this.maxSubID = Math.max(this.maxSubID, this.maxNumberOfSubscriptions);
			MAX_NUMBER_OF_SUBSCRIPTIONS = Math.max(MAX_NUMBER_OF_SUBSCRIPTIONS,
													this.maxNumberOfSubscriptions);
			
			this.areSubscriptionsRandom = true;
			if (RANDOM_ID_GENERATOR == null) {
				// Singleton
				if (s.contains(SUB_ID_RND_SEED_S)) {
					RANDOM_ID_GENERATOR_SEED = s.getInt(SUB_ID_RND_SEED_S);
				}
				RANDOM_ID_GENERATOR = new MersenneTwisterRNG(
						SeedGeneratorHelper.get16BytesSeedFromValue(RANDOM_ID_GENERATOR_SEED));
			}
			randomizeSubscriptions();
		}
		
		MAX_SUB_ID_OF_SIMULATION = Math.max(MAX_SUB_ID_OF_SIMULATION, this.maxSubID);
	}
	
	protected SubscriptionListManager(SubscriptionListManager sl) {
		this.maxSubID = sl.maxSubID;
		this.minNumberOfSubscriptions = sl.minNumberOfSubscriptions;
		this.maxNumberOfSubscriptions = sl.maxNumberOfSubscriptions;
		this.areSubscriptionsRandom = sl.areSubscriptionsRandom;
		
		this.subscriptionList = new ArrayList<Integer>();
		if (this.areSubscriptionsRandom) {
			randomizeSubscriptions();
		}
		else {
			for (Integer subID : sl.subscriptionList) {
				addSubscriptionToList(subID);
			}
			Collections.sort(this.subscriptionList);
		}
	}
	
	public SubscriptionListManager replicate() {
		return new SubscriptionListManager(this);
	}
	
	public boolean containsSubscriptionID(Integer subID) {
		if (subID == null) {
			throw new SimError("Null values as subscription IDs are not valid");
		}
		
		return subscriptionList.contains(subID);
	}
	
	public void updateSubscriptionList(ArrayList<Integer> newSubscriptionList) {
		subscriptionList = newSubscriptionList;
	}
	
	public void addSubscriptionToList(Integer subID) {
		if (subID == null) {
			throw new SimError("Null values as subscription IDs are not valid");
		}
		
		if (!containsSubscriptionID(subID)) {
			subscriptionList.add(subID);
		}
	}

	private void randomizeSubscriptions() {
		if (maxNumberOfSubscriptions <= 0) {
			return;
		}

		int generatedSubscriptionNumber = INVALID_SUB_ID;
		int rangeLength = maxNumberOfSubscriptions - minNumberOfSubscriptions + 1;
		switch (RandomDistribution) {
		case UNIFORM:
			generatedSubscriptionNumber = getRandomID(rangeLength);
			break;
		case EXPONENTIALLY_DECAYING:
			generatedSubscriptionNumber = (int) Math.floor(rangeLength * ExponentialDecayDistribution.
					extractValueFromDistribution(getRandomDouble(), DefaultDecayRate));
		}
		generatedSubscriptionNumber += minNumberOfSubscriptions;
		
		for (int i = 0; i < generatedSubscriptionNumber; ++i) {
			if (addRandomSubscriptionToList() == INVALID_SUB_ID) {
				break;
			}
		}
		
		Collections.sort(subscriptionList);
	}
	
	public int addRandomSubscriptionToList() {
		if ((subscriptionList.size() >= maxNumberOfSubscriptions) ||
			(subscriptionList.size() >= maxSubID)) {
			return INVALID_SUB_ID;
		}
		
		int subID = getRandomID(maxSubID + 1);
		while (containsSubscriptionID(subID) || (subID <= DEFAULT_SUB_ID)) {
			subID = getRandomID(maxSubID + 1);
		}
		addSubscriptionToList(subID);
		
		return subID;
	}
	
	public List<Integer> getSubscriptionList() {
		return subscriptionList;
	}
		
	public int getRandomSubscriptionFromList() {
		if (subscriptionList.size() == 0) {
			return INVALID_SUB_ID;
		}
		return subscriptionList.get(SubscriptionListManager.getRandomID(subscriptionList.size()));
	}
	
	@Override
	public String toString() {
		return subscriptionList.toString();
	}
	
}
