/**
 * 
 */
package core.disService;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.uncommons.maths.random.MersenneTwisterRNG;

import com.sun.xml.internal.messaging.saaj.packaging.mime.internet.ParseException;

import core.Settings;
import core.SimError;

/**
 * Class that implements the concept of a list of subscriptions
 * @author Alex
 *
 */
public class SubscriptionListManager {
	
	private ArrayList<Integer> subscriptionList;

	private int maxSubID;
	private int maxNumberOfSubscriptions;
	private boolean areSubscriptionsRandom;
	
	public static int MAX_SUB_ID_FOR_SIMULATION = Integer.MIN_VALUE;
	
	private static MersenneTwisterRNG RandomIDGenerator = null;
	
	/** Value to specify errors or invalid subscription IDs */
	public static final int INVALID_SUB_ID = -1;
	/** Value to be used whenever no subscriptions are generated by the node */
	public static final int DEFAULT_SUB_ID = 0;

	/** Namespace for subscriptions in the setting file -setting id ({@value}). String. */
	public static final String NAMESPACE_ID = "subscriptions";
	/** Max number of subscriptions -setting id ({@value}). int.
	 * If not specified, the value is computed from the number of subIDs specified. */
	public static final String MAX_SUB_SIZE = "maxSize";
	/** Highes valid ID for a subscription -setting id ({@value}). int.
	 * If not specified, the value is computed from the highest ID specified. */
	public static final String MAX_SUB_ID = "maxSubID";
	/** List of subscriptions the node performed -setting id ({@value}). Array of int.
	 * If not specified, the subscriptions are randomly generated. */
	public static final String GROUP_SUBSCRIPTION = "subIDs";

	/** The max number of subscriptions randomly generated a node can subscribe to */
	private static final int DEFAULT_MAX_SUB_SIZE = 5;
	/** The max subscription ID allowed for randomly generated subscriptions */
	private static final int DEFAULT_MAX_SUB_ID = 10;
	
	
	public SubscriptionListManager() {
		this.maxNumberOfSubscriptions = DEFAULT_MAX_SUB_SIZE;
		this.maxSubID = DEFAULT_MAX_SUB_ID;
		this.areSubscriptionsRandom = true;
		this.subscriptionList = new ArrayList<Integer>();
		
		MAX_SUB_ID_FOR_SIMULATION = Math.max(MAX_SUB_ID_FOR_SIMULATION, this.maxSubID);
		randomizeSubscriptions();
	}
	
	public SubscriptionListManager(Settings s) throws ParseException {
		this.subscriptionList = new ArrayList<Integer>();
		
		if (s.contains(GROUP_SUBSCRIPTION)) {
			int ids[] = s.getCsvInts(GROUP_SUBSCRIPTION);
			if (ids.length > 0) {
				Arrays.sort(ids);
				if ((ids.length > 0) && (ids[0] > 0)) {
					for (int id : ids) {
						addSubscriptionToList(id);
					}
					
					maxNumberOfSubscriptions = ids.length;
					maxSubID = ids[ids.length - 1];
					areSubscriptionsRandom = false;
				}
				else if (ids[0] == 0) {
					throw new SimError("Invalid value for a subscription ID");
				}
				
				// In case of negative values, subscriptions will be randomly generated below
			}
		}

		if (this.subscriptionList.size() == 0) {
			// Parsing was unsuccessful or the first element in the list was "-1" or lower
			if (s.contains(MAX_SUB_SIZE)) {
				this.maxNumberOfSubscriptions = s.getInt(MAX_SUB_SIZE);
			}
			else {
				this.maxNumberOfSubscriptions = DEFAULT_MAX_SUB_SIZE;
			}
			
			if (s.contains(MAX_SUB_ID)) {
				this.maxSubID = s.getInt(MAX_SUB_ID);
			}
			else {
				this.maxSubID = DEFAULT_MAX_SUB_ID;
			}			
			this.maxSubID = Math.max(this.maxSubID, this.maxNumberOfSubscriptions);
			
			this.areSubscriptionsRandom = true;
			
			randomizeSubscriptions();
		}
		
		MAX_SUB_ID_FOR_SIMULATION = Math.max(MAX_SUB_ID_FOR_SIMULATION, this.maxSubID);
	}
	
	private SubscriptionListManager(SubscriptionListManager sl) {
		this.maxSubID = sl.maxSubID;
		this.maxNumberOfSubscriptions = sl.maxNumberOfSubscriptions;
		areSubscriptionsRandom = sl.areSubscriptionsRandom;
		
		this.subscriptionList = new ArrayList<Integer>();
		if (areSubscriptionsRandom) {
			randomizeSubscriptions();
		}
		else {
			for (Integer subID : sl.subscriptionList) {
				addSubscriptionToList(subID);
			}
		}
	}
	
	public SubscriptionListManager replicate() {
		return new SubscriptionListManager(this);
	}
	
	public boolean containsSubscriptionID(Integer subID) {
		if (subID == null) {
			throw new SimError("Null values as subscription IDs are not valid");
		}
		
		return subscriptionList.contains(subID);
	}
	
	public void updateSubscriptionList(ArrayList<Integer> newSubscriptionList) {
		subscriptionList = newSubscriptionList;
	}
	
	public void addSubscriptionToList(Integer subID) {
		if (subID == null) {
			throw new SimError("Null values as subscription IDs are not valid");
		}
		
		if (!containsSubscriptionID(subID)) {
			subscriptionList.add(subID);
		}
	}

	private void randomizeSubscriptions() {
		if (maxNumberOfSubscriptions <= 0) {
			return;
		}
		
		int generatedSubscriptionNumber = getRandomID(maxNumberOfSubscriptions);
		for (int i = 0; i < generatedSubscriptionNumber; ++i) {
			if (addRandomSubscriptionToList() == SubscriptionListManager.INVALID_SUB_ID) {
				break;
			}
		}
	}
	
	public int addRandomSubscriptionToList() {
		if (subscriptionList.size() >= maxNumberOfSubscriptions) {
			return INVALID_SUB_ID;
		}
		
		int subID = getRandomID(maxSubID);
		while (containsSubscriptionID(subID)) {
			subID = getRandomID(maxSubID);
		}
		addSubscriptionToList(subID);
		
		return subID;
	}
	
	public List<Integer> getSubscriptionList() {
		return subscriptionList;
	}
		
	public int getRandomSubscriptionFromList() {
		if (subscriptionList.size() == 0) {
			return INVALID_SUB_ID;
		}
		return subscriptionList.get(SubscriptionListManager.getRandomID(subscriptionList.size() - 1));
	}
	
	static private int getRandomID(int maxSubID) {
		if (RandomIDGenerator == null) {
			RandomIDGenerator = new MersenneTwisterRNG();
			RandomIDGenerator.setSeed(System.currentTimeMillis());
		}
		
		return RandomIDGenerator.nextInt(maxSubID + 1);
	}
}
